### ISSUE TITLE
Crash to desktop on Brio v0.3.0+

### ISSUE THREAD

**Issue by MilanWinchester** [Etheirys/Brio#46] opened 2024-03-23 21:08 UTC
Game has constantly crashed 4 times after changing the clothes on my cloned character in the brio gpose mod. Has never happened before.

**Comment by Minmoose** [comment] 2024-03-25 04:18
I can't reproduce this, what other mods do you have installed?

**Comment by MilanWinchester** [comment] 2024-03-25 15:56
Just the general ones I need which are mare, penumbra, and glamourer. Mare did update last night and I tried a solo gpose with Brio and it worked. I’m a little hesitant to try it with a cloned version of myself because I change the appearance to an NPC and like I said before it’s never done this until now.

**Comment by MilanWinchester** [comment] 2024-03-25 22:15
just tried again with the cloning of myself and importing the NPC look and my game crashed within two minutes...

**Comment by HoloWise** [comment] 2024-03-26 22:32
Can't tell if it's connected to this issue or something completely different but today I crashed 2 times when posing with Brio, never happened before, Once after changing my shoes in Glamourer mid pose and once after changing skin shine level in Glamourer mid pose, Both times a short while after making those changes my game would just freeze up and crash with no logs, event viewer points at heap corruption,

**Comment by Minmoose** [comment] 2024-03-27 00:39
Undo/Redo state is not related to the crashes, that is happening because of an invalid state being saved in the Undo/Redo List, it's related to #38 

As for the crashes, I am currently investigating the crash, it seems if you have Mare & Brio enabled while in Gpose you will crash within minutes of opening Gpose, so do you have Mare installed? If so, I'm not sure if changing Glamourer items is the cause, but it might be, I'll investigate.

**Comment by Minmoose** [comment] 2024-03-27 01:33
Yea, I know Mare doesn't sync in GPose, it's quite confusing, I've only ever got it to crash with Mare enabled, but I can't find the repro for it and using debugger hasn't produced any results yet

**Comment by HoloWise** [comment] 2024-03-28 23:08
Just FYI I sent you a screenshot on Discord, talked with Dark about the issue and he threw out some loose ideas

Also I crashed again today after being in GPose for a while with no issues. Was in gpose with someone next to me and in party, they left the game, I continued posing and 1-2 minutes later it crashed. Could be a coincidence but yesterday's crash happened some time after someone came to me as I was posing so maybe a possible repro but I don't have any way to confirm this atm.

**Comment by HRFleur** [comment] 2024-03-29 09:44
I encountered super frequent crash after today's update. Everything works fine before.

**Comment by RodentCoffee** [comment] 2024-04-04 18:30
Wanted to add in on the crash report. I've never crashed this much until the recent update, and I've noticed it only happens when summoning an actor and turning them into a minion for props is an immediate crash unless I go into gpose with the minion already summoned.

E.G. I tried to summon Nana Bear through brio, crashed four times. Bought the minion, summoned it, went into gpose and never crashed.

**Comment by Minmoose** [comment] 2024-04-04 22:21
I can't reproduce this @RodentCoffee 

Is this the most recent update 0.3.0.7?

What plugins do you have installed?
Do you use TexTools or Penumbra? If so, what mods do you have installed?

![image](https://github.com/Etheirys/Brio/assets/12839703/7a6279d2-0fdd-400f-a158-8c2bcebfc7db)

**Comment by amasocen** [comment] 2024-04-05 11:29
I too have the same issue when summoning multiple acters in brio for group animations the game constantly crash without a warning. My current version is v0.3.0.5. All I installed are just brio, glamourer, and penumbra

**Comment by Minmoose** [comment] 2024-04-05 17:27
@amasocen Brio 0.3.0.5 is not compatible with FFXIV path 6.58 Hotfix 1, Update to Brio 0.3.0.7+

**Comment by Minmoose** [comment] 2024-04-09 23:14
An update to anyone who might see this. Based on some recent reports, I have two remaining theories causing the crashing, I'm going to do ***two things*** and **I will need help from the community with them**.

**First**: Tomorrow (Apr-9th EDT) I'm going to re-release Brio v0.2.3.0 made to work with FFXIV 6.58 Hotfix 1, as a testing version, *if you have been experiencing the crashing please send me a DM on how to join this Test*

**Next**: The crashing maybe due to new incompatibility with certain Penumbra mods, if anyone who is willing and has been experiencing crashing, if they could DM (on Discord(Minmoose) or Twitter(MiniatureMoosey) ) me the following:

A complete list of ***ALL*** their Penumbra mods installed &...
A complete list of ***ALL*** installed Dalamud plugins 

*Thank You* to everyone who has helped so far &, sorry for all the constant crashing! :cold_sweat:

**Comment by Minmoose** [comment] 2024-04-12 21:37
For anyone viewing this after crashing with Brio 0.3.1 and wishing to join the CrashTest over the weekend, go [here](https://etheirys-tools.gitbook.io/brio/crash-test/how-to-install-crash-test-0.2.3.1) for details.

**Comment by Desucrate** [comment] 2024-04-16 10:35
Just wanted to report another crash, I had Penumbra and Anamnesis open, though Anamnesis was not being actively used. I was fiddling around in the settings and found the keybind overlay. Hit CTRL M to test it out a couple times and got a CTD.

**Comment by Minmoose** [comment] 2024-04-24 11:43
@Desucrate This crashing with the key-bind overlay should be fixed with Brio 0.3.1.1+

**Comment by BrnctKhei** [comment] 2024-05-02 17:24
Came to add to the mix.

Ever since the most recent patch I've been dealing with the same crashes. brief freeze then exit to desktop with no errors.
The event viewer claims it's an issue with direct x11

Even without using brio for extra actors or posing it will crash. sometimes just moving the camera.

My list of plugins are as follows..

Brio
Customize+
Emote Log
ExtraChat
Glamourer
Heliophere
Honorific
Ktisis
Mare Synchronos
Moodles
Penumbra
QoL bar
Simple Heels
XICWindowResizer

Including a picture of active mods and one of the event viewer reports. the event is always the same. just a different timestamp.

![BrioCrashEvent](https://github.com/Etheirys/Brio/assets/168766322/d095d7f0-6702-45dc-bed1-a16f7a4445ef)
![FINAL FANTASY XIV 2024-05-02 11_20_21 AM](https://github.com/Etheirys/Brio/assets/168766322/786cd21a-c87d-4ffc-9577-8c9fcf72b21b)

**Comment by Minmoose** [comment] 2024-05-02 21:59
@BrnctKhei Thank you, I just pushed out an update to the CrashTest, if you could join it and see if you are still crashing, I would appreciate it!

https://etheirys-tools.gitbook.io/brio/crash-test/how-to-install-crash-test-0.2.3.2

**Comment by BrnctKhei** [comment] 2024-05-04 02:20
Finally had time to try to gpose and like clockwork, another crash.
Same List of mods and plugins as a above save for using the brio crash test version.

Including the event view and HOPEFULLY the correct dalamud log.

(Thank you for working so hard on this y'all.)
![BrioCrashMay3](https://github.com/Etheirys/Brio/assets/168766322/73b7538d-f5c0-44a3-b6fb-f6d9432974a0)
[dalamud.log](https://github.com/Etheirys/Brio/files/15206363/dalamud.log)

**Comment by Ninjacharlz** [comment] 2024-05-04 08:19
There is a very good possibility that these crashed are caused by **windows 11.**
I experienced all of these issue's myself but after i told myself "i'll download their crash log tool tommorow" i got warnings from capcom games.

making sure the windows "legacy components" are turned on fixed all of this for me.
Maybe it Can for you?

**Comment by BrnctKhei** [comment] 2024-05-04 18:01
I will try that! they were, indeed, off. turned them on and we'll see if that helps. Thanks!

**Comment by Desucrate** [comment] 2024-05-04 23:43
> There is a very good possibility that these crashed are caused by **windows 11.** I experienced all of these issue's myself but after i told myself "i'll download their crash log tool tommorow" i got warnings from capcom games.
> 
> making sure the windows "legacy components" are turned on fixed all of this for me. Maybe it Can for you?

My crash was on Win 10, just as a note for this.

**Comment by BrnctKhei** [comment] 2024-05-05 04:12
Unfortunately turning legacy components did not fix the issue. I just crashed again. just moving the camera. most of my crashes happen while moving the camera.

Including dalamud log again for tonight's crash.

[dalamud (2).log](https://github.com/Etheirys/Brio/files/15211723/dalamud.2.log)

**Comment by BrnctKhei** [comment] 2024-05-05 06:14
just a note here. it'd a bit early to tell for sure but I've started leaving delimit camera and disable collision off and haven't had a crash yet.

**Comment by Minmoose** [comment] 2024-05-05 21:38
@BrnctKhei The log you provided indicates that you aren't using the CrashTest, I've just once again update the Test to 0.2.3.3 so if you could join the test and see if that fixes your crashing I would, appreciate it!

@Ninjacharlz Have you been using the CrashTest? And have you experienced a crash in the last two days?

**Comment by BrnctKhei** [comment] 2024-05-06 01:50
Then that must be the wrong log. I'll figure out where the correct one is.

**Comment by Ninjacharlz** [comment] 2024-05-08 13:10
> @BrnctKhei The log you provided indicates that you aren't using the CrashTest, I've just once again update the Test to 0.2.3.3 so if you could join the test and see if that fixes your crashing I would, appreciate it!
> 
> @Ninjacharlz Have you been using the CrashTest? And have you experienced a crash in the last two days?

i litterally had another crash today(it appears the problem wasn't resolved), i have not been using the crash test. i will do so now and see if i can get another crash today.

**Comment by Ninjacharlz** [comment] 2024-05-08 13:35
i was posing with multiple characters.
i had the following plugins running.

Blue mage helper
Brio - crashtest 0.2
Character data sync by goat.
Chat bubbles.
Customize+
Glamourer
Heliosphere.
Mare Synchronos
Penumbra
Moodles.
Price Insight
simple heels.

i usually have all of these running.
a while ago i posted that enabling legacy components onmy windows 11 fixed issue's.
it KINDA did.  crashes aren't as frequent or AS instantly as before.

[dalamud.log](https://github.com/Etheirys/Brio/files/15249541/dalamud.log)

**Comment by BrnctKhei** [comment] 2024-05-10 19:09
> Came to add to the mix.
> 
> Ever since the most recent patch I've been dealing with the same crashes. brief freeze then exit to desktop with no errors. The event viewer claims it's an issue with direct x11
> 
> Even without using brio for extra actors or posing it will crash. sometimes just moving the camera.
> 
> My list of plugins are as follows..
> 
> Brio Customize+ Emote Log ExtraChat Glamourer Heliophere Honorific Ktisis Mare Synchronos Moodles Penumbra QoL bar Simple Heels XICWindowResizer
> 
> Including a picture of active mods and one of the event viewer reports. the event is always the same. just a different timestamp.
> 
> ![BrioCrashEvent](https://private-user-images.githubusercontent.com/168766322/327522628-d095d7f0-6702-45dc-bed1-a16f7a4445ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjgyODMsIm5iZiI6MTcxNTM2Nzk4MywicGF0aCI6Ii8xNjg3NjYzMjIvMzI3NTIyNjI4LWQwOTVkN2YwLTY3MDItNDVkYy1iZWQxLWExNmY3YTQ0NDVlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxOTA2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzg3MTk1NTRhMzc4MzhkZDIwNTM4NGI3ZTA5OTdlY2IwOGFkZTM1NWI1M2I4MmI5NzgzMzFkZGI1NDFkNjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SXpShxraEyoo8Cyqi-wyF_7l_yHlqok28yxEJzCIUX8) ![FINAL FANTASY XIV 2024-05-02 11_20_21 AM](https://private-user-images.githubusercontent.com/168766322/327522630-786cd21a-c87d-4ffc-9577-8c9fcf72b21b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNjgyODMsIm5iZiI6MTcxNTM2Nzk4MywicGF0aCI6Ii8xNjg3NjYzMjIvMzI3NTIyNjMwLTc4NmNkMjFhLWM4N2QtNGZmYy05NTc3LThjOWZjZjcyYjIxYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxOTA2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGM5OWI3MmNmMmI0YjgxOWZlNjI2OTQ3ODE1NmQ4OTJmMDQxMTUzZjI5MmNlOTM5ODRhMTBlNWI0N2QyODAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BkQ42J0JtRknh6_1fdGTwcU9Yqt6YWmcNkPLzpk1MWw)

Had another crash today. Took much longer to crash than usual and I had a fair few brio generated actors.

Same mods, same plugins.

I HOPE that I'm including the correct log file because I am, indeed, using the crash test version
[dalamud.log](https://github.com/Etheirys/Brio/files/15279033/dalamud.log)

**Comment by Minmoose** [comment] 2024-05-10 20:21
@BrnctKhei Just to confirm, you are using CrashTest v0.2.3.5?

**Comment by BrnctKhei** [comment] 2024-05-10 23:52
Correct.

![20240510_175209](https://github.com/Etheirys/Brio/assets/168766322/2535f583-8142-4893-a21c-efaadef81c68)

**Comment by BrnctKhei** [comment] 2024-05-18 20:47
Dunno if it helps but crashed again for me..

Same mods/pugins Only thing different is that I have downloaded and installed another clothing mod
Lord Errant for Ladies [Bibo+]

Crashed last night before I had that mod though.

I can pose to my heart's content. For me the crashes always happen when I'm moving the camera.

I can only hope I'm including the right dalamud log because I play the game and gpose under my login on my shared PC but my husband started modding under his login first. The log I'm sending in from the file location in my user folder so I hope it's the correct one.

I apologize if I'm annoying or stupid. I'm doing my best to help with identifying the culprit of the crashes.

[dalamud may18.log](https://github.com/Etheirys/Brio/files/15366822/dalamud.may18.log)

**Comment by Minmoose** [comment] 2024-05-19 01:26
@BrnctKhei Your fine you've not been annoying or stupid, I'm sorry I've been slow to respond I have been unable to do much the last few weeks because of constant life emergencies and yes you are submitting the right logs, if the camera is causing the crashing it won't be Brio that's the culprit, but I think that it's unlikely it's the camera causing crashing anyway, you are unfortunately the only one that is still reporting crashing with the current version of the CrashTest, there is a known crash with the current CrashTest but it's not a crash to desktop like what you are experiencing so I'm not sure if your crashing is because of Brio and unfortunately the log isn't much help with your crashing. Have you tried to validate the game files with the Dalamud launcher, and are you PC's drivers up to date?

**Comment by Ninjacharlz** [comment] 2024-05-20 17:19
[dalamud.log](https://github.com/Etheirys/Brio/files/15380013/dalamud.log)

New dalamud.log file from today.

Same plugins as last time.
This time the crash happened after i opened the menu for "advanced" editing to change the character "wetness".

**Comment by Minmoose** [comment] 2024-07-01 17:56
Closed due to pending rewrite for Dawntrail

I've traced this issue back to #37, I believe this crash was the same one I observed in the Feb 26 comment

**Closed by Minmoose** 2024-07-01 17:56 UTC
Labels: bug, help wanted, question
